spring:
  application:
    name: demo-spring-data-jpa

  h2:
    console:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:demo_spring_data_jpa

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080